AlphaProject/Controllers/PanelController.cs
using AlphaProject.Entity;
using AlphaProject.Infrastrature;
using AlphaProject.Models;
using AlphaProject.Service.AppUserService;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AlphaProject.Controllers
{
    public class PanelController : Controller
    {
        #region ################################# Const And Values #################################
        private readonly IAppUserService _appUserService;
        private AppUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
        private IAuthenticationManager AuthManager => HttpContext.GetOwinContext().Authentication;

        public PanelController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }
        #endregion

        #region ###################################### Index #######################################
        public ActionResult Index(string msg = "")
        {
            if (msg != "")
            {
                if (msg == "-1")
                    ViewBag.ErrorMSG = "نام کاربری یا کلمه عبور صحیح نمیباشد";
                ViewBag.ErrorType = "0";
            }
            return View();
        }
        #endregion

        #region #################################### Operation ##################################### 

        [HttpPost]
        public async Task<ActionResult> Login(AccountModel model)
        {
            try
            {
                AppUser userIdentity = _appUserService.GetUserAccessByUserAndPass(model.Username, model.Password);
                if (userIdentity == null && userIdentity.status == AppUser.StatusUser.Active && userIdentity.type == AppUser.TypeUser.Admin)
                {
                    ClaimsIdentity ident = await UserManager.CreateIdentityAsync(userIdentity, DefaultAuthenticationTypes.ApplicationCookie);
                    AuthManager.SignOut();
                    AuthManager.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = false
                    }, ident);
                    return RedirectToAction("Index", "DashbordAdmin", new { area = "Admin" });
                }
                else if (userIdentity == null && userIdentity.status == AppUser.StatusUser.Active && userIdentity.type == AppUser.TypeUser.User)
                {
                    ClaimsIdentity ident = await UserManager.CreateIdentityAsync(userIdentity, DefaultAuthenticationTypes.ApplicationCookie);
                    AuthManager.SignOut();
                    AuthManager.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = false
                    }, ident);
                    return RedirectToAction("Index", "DashbordUser", new { area = "User" });
                }
                else if (true)
                {
                    return RedirectToAction("Index", new { msg = "-1" });
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", new { msg = "-1" });
            }
        }

        #endregion
    }
}

AlphaProject/Views/Panel/Index.cshtml
@model  AlphaProject.Models.AccountModel
@{
    ViewBag.Title = "ورود به پنل";
}

<html lang="fa">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ورود به پنل مدیریت</title>
</head>
<body class="bg-white" style="margin:0 auto">
    @using (Html.BeginForm("Login", "Panel", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="ErrorMsg" id="hdfMsg" value="@ViewBag.ErrorMSG" />
        <input type="hidden" name="ErrorType" id="hdfType" value="@ViewBag.ErrorType" />
        <h3>ورود به پنل مدیریت</h3>
        <div>
            <div class="group material-input">
                @Html.TextBoxFor(x => x.Username)
                <label>نام کاربری</label>
            </div>
            <div class="group material-input">
                @Html.PasswordFor(x => x.Password)
                <label>رمز عبور</label>
            </div>
        </div>
        <button type="submit" class="btn btn-lg btn-gradient-01">
            ورود
        </button>
    }
</body>
</html>